In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
df[1:3]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0

In [ ]:
df.iloc[1:3,1:10]

latitude  housing_median_age  total_rooms  total_bedrooms  population  \
1     34.40                19.0       7650.0          1901.0      1129.0   
2     33.69                17.0        720.0           174.0       333.0   

   households  median_income  median_house_value  
1       463.0         1.8200             80100.0  
2       117.0         1.6509             85700.0

In [ ]:
df.iloc[[1,2,3],1]

1    34.40
2    33.69
3    33.64
Name: latitude, dtype: float64

In [ ]:
x = np.random.normal(loc=0,scale=1,size=1000)


In [ ]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
from sklearn.linear_model import LinearRegression as lr

In [ ]:
x = df.iloc[:,0:8]
y = df.iloc[:,8]

In [ ]:
y

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

In [ ]:
algo = LinearRegression()

In [ ]:
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

In [ ]:
y

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
algo.fit(x,y)

LinearRegression()

In [ ]:
test = pd.read_csv("/content/sample_data/california_housing_test.csv")
pred = algo.predict(test.iloc[:,:8])
pred

array([352812.31112454, 212717.70074518, 272344.69951888, ...,
        88220.58643733, 146374.67481457, 456779.61107787])

In [ ]:

ans = np.array(test.iloc[:,8])

In [ ]:
sub = np.abs(np.subtract(pred,ans))

In [ ]:
prob = np.divide(sub,ans)
prob

array([0.02353441, 0.20519944, 0.00681959, ..., 0.42291268, 0.09923277,
       0.0864426 ])

In [ ]:
np.average(np.subtract(np.array([1]*17000),np.average(prob)))

0.7027012595540144

In [ ]:
1-prob

array([0.97646559, 0.79480056, 0.99318041, ..., 0.57708732, 0.90076723,
       0.9135574 ])

In [ ]:
prob-sub

array([ -8112.28759013, -36217.49554574,  -1844.69269929, ...,
       -26220.16352464, -16125.22595266, -43221.30247953])